default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5433
      dbname: analytics
      schema: public
      threads: 1
