default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: postgres
      password: postgres
      port: "{{ env_var('DBT_PORT', '5433') | int }}"
      dbname: analytics
      schema: public
      threads: 1
