services:
  mock-api:
    image: python:3.10-slim
    container_name: day56-mock-api
    working_dir: /app
    command: python -m http.server 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  warehouse-postgres:
    image: postgres:15
    container_name: day56-warehouse-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5434:5432"
    volumes:
      - warehouse-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "warehouse"]
      interval: 10s
      retries: 5
      start_period: 5s

  airflow-postgres:
    image: postgres:15
    container_name: day56-airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow", "-d", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

  airflow-init:
    image: day56-airflow-spark-java-fixed:latest
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: day56-airflow-init
    depends_on:
      airflow-postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      JAVA_HOME: /usr/lib/jvm/default-java
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username admin \
          --firstname Yu \
          --lastname Zhang \
          --role Admin \
          --email admin@example.com \
          --password admin || true
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/airflow/data

  airflow-webserver:
    image: day56-airflow-spark-java-fixed:latest
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: day56-airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      warehouse-postgres:
        condition: service_healthy
      mock-api:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      JAVA_HOME: /usr/lib/jvm/default-java
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: airflow_secret_key
      SPARK_MASTER: local[*]
      API_URL: http://mock-api:8000/sales_events.json
      WAREHOUSE_JDBC_URL: jdbc:postgresql://warehouse-postgres:5432/warehouse
      WAREHOUSE_USER: postgres
      WAREHOUSE_PASSWORD: postgres
    command: webserver
    ports:
      - "8082:8080"
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/airflow/data

  airflow-scheduler:
    image: day56-airflow-spark-java-fixed:latest
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: day56-airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      warehouse-postgres:
        condition: service_healthy
      mock-api:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      JAVA_HOME: /usr/lib/jvm/default-java
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: airflow_secret_key
      SPARK_MASTER: local[*]
      API_URL: http://mock-api:8000/sales_events.json
      WAREHOUSE_JDBC_URL: jdbc:postgresql://warehouse-postgres:5432/warehouse
      WAREHOUSE_USER: postgres
      WAREHOUSE_PASSWORD: postgres
    command: scheduler
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./spark_jobs:/opt/airflow/spark_jobs
      - ./data:/opt/airflow/data

volumes:
  airflow-postgres-data:
  warehouse-postgres-data:
